spring:
  dbhandlers:
    S3:
      abstractbucket: phenomics-article-abstracts-dev
      l2cachefiltersbucket: phenomics-graph-l2cache-filters
      l2cachearticlesbucket: phenomics-graph-l2cache-articles
    dynamodb:
      articletablename: phenomics-articles-dev
      annotationtablename: phenomics-annotations-dev
      subscriptiontablename: phenomics-subscriptions-dev
      l2cachetablename: phenomics-l2-cache
    graphdb:
      endpoint: http://neo4j.phenomics.awsinternal.dev.:7474/
      username: neo4j
      password: Neo4j@1Dev
      live:
        endpoint: bolt://neo4j.phenomics.awsinternal.dev.:7687/
        username: neo4j
        password: Neo4j@1Dev
      historical:
        endpoint: bolt://52.62.200.154:7687/
        username: neo4j
        password: Neo4j@1Prod

  notificationconnector:
    endpoint: http://cluster.phenomics.awsinternal.dev.:9090

  affinityconnector:
    endpoint: http://cluster.phenomics.awsinternal.dev.:9020

  lambdaconnector:
    workerfunctionname: pubmed-ingestion-worker-lambda

  subscriptionservice:
    subscriptiontime: 2
logging:
  path: ./logs/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %p | source= %c{1.} | %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %p | stackName=phenomics | appName=annotation-pipepline | source= %c{1.} | %msg%n"
  level:
    root: WARN
    au.org.garvan.kccg.annotations.pipeline: INFO

server:
    port: 9080
